import type { Treatment, Specialist } from "./types"

export const mockTreatments: Treatment[] = [
  {
    id: "mock-1",
    name: "Skin Cancer Screening",
    category: "medical",
    tagline: "Early detection saves lives",
    description: "Full-body mole mapping and dermoscopy with AI-assisted analysis.",
    duration: "60 min",
    image_url: "/treatment-medical-1.webp",
    sort_order: 1,
  },
  {
    id: "mock-2",
    name: "Medical Dermatology Consultation",
    category: "medical",
    tagline: "Expert diagnosis, lasting clarity",
    description: "Comprehensive skin health assessment for acne, eczema, psoriasis, and more.",
    duration: "45 min",
    image_url: "/treatment-medical-2.webp",
    sort_order: 2,
  },
  {
    id: "mock-3",
    name: "Mole Mapping & Dermoscopy",
    category: "medical",
    tagline: "Precision in every pixel",
    description: "Digital mole tracking with high-resolution dermoscopy over time.",
    duration: "45 min",
    image_url: "/treatment-medical-3.webp",
    sort_order: 3,
  },
  {
    id: "mock-4",
    name: "Acne & Rosacea Treatment",
    category: "medical",
    tagline: "Clear skin, restored confidence",
    description: "Medical-grade protocols tailored to your skin type and severity.",
    duration: "30 min",
    image_url: "/treatment-medical-4.webp",
    sort_order: 4,
  },
  {
    id: "mock-5",
    name: "Laser Resurfacing",
    category: "aesthetic",
    tagline: "Reveal the skin beneath",
    description: "Fractional laser for texture, tone, and scar revision.",
    duration: "60 min",
    image_url: "/treatment-aesthetic-1.webp",
    sort_order: 5,
  },
  {
    id: "mock-6",
    name: "Chemical Peels",
    category: "aesthetic",
    tagline: "Luminous, renewed skin",
    description: "Medical-grade peels for pigmentation, fine lines, and radiance.",
    duration: "45 min",
    image_url: "/treatment-aesthetic-2.webp",
    sort_order: 6,
  },
  {
    id: "mock-7",
    name: "Non-Surgical Rejuvenation",
    category: "aesthetic",
    tagline: "Subtle. Natural. You.",
    description: "Dermal fillers and neuromodulators for refined, natural-looking results.",
    duration: "45 min",
    image_url: "/treatment-aesthetic-3.webp",
    sort_order: 7,
  },
  {
    id: "mock-8",
    name: "Medical-Grade Skincare",
    category: "aesthetic",
    tagline: "Your daily dermatology ritual",
    description: "Personalized prescription skincare programs backed by clinical evidence.",
    duration: "30 min",
    image_url: "/treatment-aesthetic-4.webp",
    sort_order: 8,
  },
]

export const mockSpecialists: Specialist[] = [
  {
    id: "mock-s1",
    name: "Dr. Elena Marchetti",
    title: "Medical Director",
    specialty: "Medical & Oncological Dermatology",
    bio: "Board-certified dermatologist with 15 years specializing in early skin cancer detection and dermoscopy. Trained at the San Gallicano Dermatological Institute, Rome.",
    photo_url: "/specialist-elena.webp",
    sort_order: 1,
  },
  {
    id: "mock-s2",
    name: "Dr. James Whitfield",
    title: "Lead Aesthetic Dermatologist",
    specialty: "Aesthetic & Laser Medicine",
    bio: "Pioneer in fractional laser resurfacing and non-surgical rejuvenation. Former faculty at the University of Cambridge Department of Dermatology.",
    photo_url: "/specialist-james.webp",
    sort_order: 2,
  },
  {
    id: "mock-s3",
    name: "Dr. Sofia Nakamura",
    title: "Consultant Dermatologist",
    specialty: "Pediatric & General Dermatology",
    bio: "Specialist in pediatric skin conditions, eczema, and adolescent acne. Author of three textbooks on clinical pediatric dermatology.",
    photo_url: "/specialist-sofia.webp",
    sort_order: 3,
  },
  {
    id: "mock-s4",
    name: "Dr. Amara Okafor",
    title: "Dermatologist & Researcher",
    specialty: "Pigmentary Disorders & Ethnic Skin",
    bio: "Leading researcher in melasma, post-inflammatory hyperpigmentation, and skin-of-color dermatology. Published in over 40 peer-reviewed journals.",
    photo_url: "/specialist-amara.webp",
    sort_order: 4,
  },
]

export const mockTimeSlots = [
  "09:00",
  "10:00",
  "11:00",
  "14:00",
  "15:00",
  "16:00",
]
